mysite/blog/urls.py
from django.urls import path

from . import views

app_name = "blog"
urlpatterns = [
    path("",views.main_page, name="main_page"),
    path("blogs/",views.BlogListView.as_view(), name="blog_list"),
    path("blog_post/<int:pk>/", views.BlogpostView.as_view(), name="blogpost"),
    path("newest_blog/", views.newest_blog, name="newest_blog"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

mysite/blog/models.py
from django.db import models
from django.contrib import admin


# Create your models here.


class Blogpost(models.Model):

    def __str__(self):
        return self.blog_heading

    blog_heading = models.CharField(max_length=200)
    blog_text = models.TextField(max_length=20000, default="Text")
    pub_date = models.DateTimeField("date published")
    description = models.CharField(max_length=200, default="Description")

mysite/blog/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from .models import Blogpost
from django.shortcuts import redirect
from django.urls import reverse

# Create your views here.


def main_page(request):
    return render(request, "blog/index.html", {"posts": Blogpost.objects.all()[:5]})


def newest_blog(request):
    return redirect(reverse("blog:blogpost", kwargs={"pk": 1}))


class BlogListView(generic.ListView):
    template_name = "blog/blog_list.html"
    context_object_name = "blog_post_list"


    def get_queryset(self):
        return Blogpost.objects.order_by("pub_date")
    

class BlogpostView(generic.DetailView):
    model = Blogpost
    template_name = "blog/blogpost.html"

    def get_queryset(self):
        return Blogpost.objects.all()

mysite/blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
</head>
<body>
    <nav class="navbar">
        <div class="brand-title">Martins Blog</div>
        <a href="#" class="toggle-button">
          <span class="bar"></span>
          <span class="bar"></span>
          <span class="bar"></span>
        </a>
        <div class="navbar-links">
          <ul>
            <li><a href="{% url 'blog:main_page' %}">Home</a></li>
            <li><a href="{% url 'blog:blog_list' %}">Blogs</a></li>
            <li><a href="{% url 'blog:newest_blog' %}">Newest Blog</a></li>
          </ul>
        </div>
    </nav>
    {% block content %}{% endblock %}


    <h2>THANK YOU FOR VISITING @ Martin Jaros</h2>
    <footer>Copyright r 2024</footer>
</body>
</html>

mysite/blog/templates/blog/blog_list.html
{% extends 'blog/base.html' %}


{% block content %}

{% if blog_post_list %}
<ul class="BlogListPage_list">
    {% for post in blog_post_list %}
    <li>
      <h1 class="BlogListPage_heading"><a href="{% url 'blog:blogpost' post.id %}">{{post.blog_heading}}</a></h1>
      <p class="BlogListPage_published">Published: {{post.pub_date}}</p>
      <p class="BlogListPage_description">{{post.description}}</p>
    </li>
    {% endfor %}
</ul>
{% else %}
    <h1>No blog posts are available.</h1>
{% endif %}

{% endblock %}

mysite/blog/templates/blog/blogpost.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="blogpost">


    <h1>{{blogpost.blog_heading}}</h1>
    <p>{{blogpost.blog_text}}</p>
    

    
</div>
{% endblock %}

mysite/blog/templates/blog/index.html
{% extends 'blog/base.html' %}


  {% block content %}
    <section class="welcome_section">
        <h1 class="welcome_heading">WELCOME TO MY BLOG</h1>
        <p class="welcome_text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam totam ipsa dicta veritatis atque iusto hic libero earum molestiae, reprehenderit magnam quasi eaque eum illum fuga? Reiciendis itaque ipsum voluptate!</p>
    </section>


    <section class="list_section">
        <h1>Recent blogs:</h1>
        <ul class="blog_preview">
        {% for post in posts %} 
            <li>
                <h2><a href="{% url 'blog:blogpost' post.id %}">{{post.blog_heading}}</a> </h2>
                <p>{{post.pub_date}}</p>
            </li>
            <li>{{ post.blog_text|slice:":120"}} ...</li>
        {% endfor %}
        </ul>
        <h2><a href="{% url 'blog:blog_list' %}">More blogs</a></h2>
    </section>
  {% endblock %}
    